notifications:
    email: false
language: python
python:
    - "3.6"

install:
    - pip install codecov
    - pip install -r requirements.txt
before_script: cd mini_maze
script:
    - coverage run manage.py test
after_success:
    - codecov
